spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://HOST_HERE:PORT_HERE/DATABASE_HERE"
    username: "USERNAME_HERE"
    password: "PASSWORD_HERE"
    hikari:
      auto-commit: false
      pool-name: mute-pool
      minimum-idle: 10
      maximum-pool-size: 20
      connection-timeout: 60000
      max-lifetime: 1800000
      idle-timeout: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update